#!/bin/sh
#
if [ @MACHINE@ = x1e ] ; then
#PBS -l mppe=1
#PBS -N co2
#
   . /opt/modules/modules/init/sh
   module load open pbs PrgEnv
fi

set -x

CON_DIR=/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con
MODEL_DIR=/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp
BIN_DIR=/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin
INSTALL_DIR=$BIN_DIR

co2ppmv=348

if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
else
        rm -f fort.[0-9]* 2>/dev/null
fi

ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp       fort.1
ln -fs co2con                             fort.66
ln -fs co2output                          fort.16
ln -fs $CON_DIR/cns_${co2ppmv}_490850.asc fort.61
ln -fs $CON_DIR/cns_${co2ppmv}_490670.asc fort.62
ln -fs $CON_DIR/cns_${co2ppmv}_670850.asc fort.63

INPUT=co2.parm
echo $co2ppmv. >co2.parm

if [ linux_intel = es ] ; then
dirhere=`pwd`
cat >~/co2_gb.sh <<EOF
#!/bin/sh
cd $dirhere
 ./co2.x <co2.parm >co2.out 2>&1
EOF
	chmod 755 ~/co2_gb.sh
	rexec gbnode000 -l @USERNAME@ ./co2_gb.sh
else
	 $BIN_DIR/co2.x <co2.parm >co2.out 2>&1
fi

if [ $? -ne 0 ] ; then
	echo `date` - co2 execution failed
	exit 8
fi
rm -f fort.[0-9]*
echo "co2con created on `date`" >$INSTALL_DIR/.co2
