#!/bin/sh
#
# thread or hybrid options
#
if [ mpi = thread -o mpi = hybrid ] ; then
	OMP_NUM_THREADS=1
	export OMP_NUM_THREADS
	if [ linux_intel = cray -o linux_intel = t90 ] ; then
		NCPUS=1
		export NCPUS
	fi
	if [ linux_intel = sgi -o linux_intel = origin ] ; then
		MP_SET_NUMTHREADS=1
		export MP_SET_NUMTHREADS
	fi
	if [ linux_intel = dec ] ; then
		MP_STACK_SIZE=500000000
        export MP_STACK_SIZE
	fi
    if [ linux_intel = ibmsp ] ; then
		XLSMPOPTS="stack=256000000"
		export XLSMPOPTS
    fi
    if [ linux_intel = linux_pgi ] ; then
		#MP_STACKZ=200M; export MP_STACKZ
		MPSTKZ=200M; export MPSTKZ
		PGI_TERM=trace; export PGI_TERM
    fi
#    if [ linux_intel = linux_intel ] ; then
#		#KMP_STACKSIZE=100M; export KMP_STACKSIZE
#    fi
    if [ linux_intel = x1e ] ; then
		X1_STACK_SIZE=0x180000000; export X1_STACK_SIZE
		OMP_THREAD_STACK_SIZE=500000000; export OMP_THREAD_STACK_SIZE
    fi
fi
#
runscr=/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/runscr
#
# Environmental variables for mpi mode
#
if [ mpi = mpi -o mpi = thread -o mpi = hybrid ]; then

if [ nml = nml -a linux = linux ] ; then
   FCSTENV='mpirun -machinefile $PBS_NODEFILE -np 12'
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='pbs'
   BATCHstatus='qstat'
elif [ nml = kisti -a linux = linux ]; then
   if [ \( "$MPI" = "" -a "$MPINAME" = "openmpi" \) -o "$MPI" = "openmpi" ]; then
     #openmpi 
     FCSTENV='mpirun -mca btl self,openib -mca plm_rsh_num_concurrent 400 -mca oob_tcp_listen_mode listen_thread -mca plm_rsh_tree_spawn 1 -np $NSLOTS'
   else
     #mvapich, mvapich2
     FCSTENV='mpirun_rsh -hostfile $TMPDIR/machines -np $NSLOTS'
   fi
   BATCHQUE='qsub'
   BATCHdepend='-hold_jid '
   BATCHtype='sge'
   BATCHstatus='qstat'
elif [ nml = kisti -a linux_intel = ibmsp ]; then
   FCSTENV='poe'
   BATCHQUE='llsubmit'
   BATCHdepend=''
   BATCHtype='lls'
   BATCHstatus='llq'
elif [ nml = kaf -a linux = linux ]; then
   FCSTENV='mpiexec_mpt -v -np 12'
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='pbspro'
   BATCHstatus='qstat'
elif [ nml = haenam -a linux = linux ]; then
   FCSTENV='aprun -n 12'
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='haenam'
   BATCHstatus='qstat'
elif [ nml = kiaps -a linux = linux ]; then
   if [ `echo $MPI_RUN | grep mpich2   | wc -l` -eq 1 ]; then      # gaon1 mpich2
     FCSTENV='mpirun -np 12 -f $PBS_NODEFILE'
   else
     FCSTENV='mpirun -machinefile $PBS_NODEFILE -np 12'
   fi
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='pbspro'
   BATCHstatus='qstat'
elif [ nml = kiapsrt -a linux = linux ]; then
   if [ `echo $MPI_RUN | grep mpich2   | wc -l` -eq 1 ]; then      # gaon1 mpich2
     FCSTENV='mpirun -np 12 -f $PBS_NODEFILE'
   else
     FCSTENV='mpirun -machinefile $PBS_NODEFILE -np 12'
   fi
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='kiapsrt'
   BATCHstatus='qstat'
elif [ nml = apcc -a linux = linux ]; then
   FCSTENV='mpirun -machinefile $PBS_NODEFILE -np 12'
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='pbs'
   BATCHstatus='qstat'
elif [ nml = ncar -a linux = linux ]; then
   FCSTENV='mpirun.lsf'
   BATCHQUE='bsub'
   BATCHdepend='-w'
   BATCHtype='bsub'
   BATCHstatus='bjobs'
elif [ nml = noaa -a linux = linux ]; then
   FCSTENV='mpiexec_mpt -v -np 12'
#   BATCHQUE='qsub -l vmem=3GB'
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='pbsnoaa'
   BATCHstatus='qstat'
elif [ nml = kesti -a linux = linux ] ; then
   FCSTENV='mpirun -machinefile $PBS_NODEFILE -np 12'
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='pbs'
   BATCHstatus='qstat'
elif [ nml = snu -a linux = linux ] ; then
   FCSTENV='mpirun -machinefile $PBS_NODEFILE -np 12'
   BATCHQUE='qsub'
   BATCHdepend='-W depend=afterok:'
   BATCHtype='pbs'
   BATCHstatus='qstat'
elif [ nml = kma -a linux_intel = x1e ]; then
   FCSTENV=' -n 12 -N 12 -d 1 -m exclusive'
   BATCHQUE=''
   BATCHdepend=''
   BATCHtype='dec'
elif [ linux_intel = mac ]; then
   FCSTENV='mpirun -wd $here_dir'
   BATCHQUE=''
   BATCHdepend=''
   BATCHtype='mac'
elif [ linux_intel = dec ]; then
   FCSTENV='dmpirun -np 12'
   BATCHQUE=''
   BATCHdepend=''
   BATCHtype='dec'
   ulimit -d 4232635
   ulimit -s 1024000
else
   FCSTENV='mpirun -machinefile ~/mpd.hosts -np 12'
   BATCHQUE=''
   BATCHdepend=''
   BATCHtype='dec'
fi

else  # for single run
   FCSTENV=''
   BATCHQUE=''
   BATCHdepend=''
   BATCHtype='dec'
fi
if [ mpi = thread ]; then
   FCSTENV=''
fi
#
# Make fcst, pgb, fgb scripts with FCSTENV and header
#
   if [ mpi = single ]; then
     header1=${BATCHtype}_single.head
   else
     header1=${BATCHtype}_mpi.head
   fi
   header2=${BATCHtype}_single.head
   #
   # parallel or serial
   #
   files="fcst r_fcst r_cpl_fcst fcst_omp"
   for file in $files; do
     sed -n "s%@FCSTENV@%${FCSTENV}%g ; /end_of_header/,\$p" \
             $runscr/$file > $runscr/$file.a
     cat $runscr/$header1 $runscr/$file.a > $runscr/$file
     rm -f $runscr/$file.a
     chmod a+x $runscr/$file
   done
   #
   # serial
   #
   files="pgb fgb sgb post_omp post_all r_post_all grims_rt_post"
   for file in $files; do
     sed -n "s%@FCSTENV@%${FCSTENV}%g ; /end_of_header/,\$p" \
             $runscr/$file > $runscr/$file.a
     cat $runscr/$header2 $runscr/$file.a > $runscr/$file
     rm -f $runscr/$file.a
     chmod a+x $runscr/$file
   done
#
#  namelist convention for ibmsp
#
if [ linux_intel = ibmsp ] ; then
	PARTHDS=1
	XLSMPOPTS="parthds=${PARTHDS}"
	export XLSMPOPTS
#	XLFRTEOPTS="namelist=old"
#	export XLFRTEOPTS
	MP_SHARED_MEMORY=yes
	export MP_SHARED_MEMORY
	SPINLOOPTIME=5000
	export SPINLOOPTIME
	ulimit -d unlimited
	ulimit -s unlimited
fi
if [ linux_intel = mac ] ; then
#   export XLFRTEOPTS="namelist=old"  # (SCC no longer needed  01/07/05)
    if [ mpi = mpi ] ; then
       lamboot -v $HOME/lamhosts      # activate lam MPI universe on Mac
    fi
fi
