#!/bin/sh
#PBS -l nodes=3:ppn=36
#PBS -V
##PBS -j eo
#------------------------------------------------------------------end_of_header
set -ax
#
if [ linux_intel = linux_pgi ]; then
export NO_STOP_MESSAGE=1
fi
#export MPIEXEC_TIMEOUT=15   # to prevent qdel error
#
#  execute forecast.
#
#  $1 ... FCSTENV required for mpi runs on origin (this should be the
#         last argument since it can be blank.
#         Note that script referrs $1 as $* since it is a string of
#         characters separated by blanks so that it takes all the arguments
#         as one.
#
if [ "$EXECDIR" != "" ]; then
	cd $EXECDIR
fi
#
PROG=fcst
#
# SWRMDC
#
if [ "" = "yes" ]; then
	mon=01
	while [ $mon -le 12 ]; do
		ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/global_aeropac3a.m${mon}.txt .
		mon=`expr $mon + 1`
		if [ $mon -lt 10 ]; then
			mon=0$mon
		fi
	done
fi

#
#  Execute forecast
#
if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
else
        rm -f fort.[0-9]* 2>/dev/null
fi

if [ linux_intel = cray -o linux_intel = t90 -o linux_intel = t3e ] ; then
	assign -R
fi
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp     fort.1
ln -fs $EXECDIR/co2con                  fort.15
ln -fs $EXECDIR/mtnvar                  fort.24
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/o3prod.clim.asc        fort.28
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/o3loss.clim.asc        fort.29
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/flwdirGSWP2.hlf.asc    fort.41
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/tune.t42l18.amip.ewmrg fort.43
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/gcmo3.asc              fort.48
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/RRTMG_LW_DATA_DBL      RRTMG_LW_DATA
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/RRTMG_SW_DATA_DBL      RRTMG_SW_DATA
if [ "0" = 1 ]; then
	# input sigma
    ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/verlev.asc         fort.11
	# output
    ln -fs fcst.bin  				     fort.333
	fh=00
else
	fh=`/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/etc/fhour sigit`
fi
if [ linux_intel = x1e ]; then
	assign -D stderr              		fort.6
	#buffer unit is 4096-byte blocks.
	ln -fs fcstout.ft$fh -b 1          fort.6
fi

rm -f $PROG.x
if [ ! -s /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/fcst.x ] ; then
	echo /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/fcst.x does not exist
	exit 8
fi
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/fcst.x $PROG.x
 #soojin_couple
#for nemo run
ln -fs /rhome/soo/NEMO/couple/couple_ice/nemo-4.2.2/tests/test_CPL_OASIS/BLD/bin/nemo.exe ./nemo
ln -fs /rhome/soo/NEMO/couple/couple_ice/nemo-4.2.2/tests/test_CPL_OASIS/EXP00/namelist_cfg .
ln -fs /rhome/soo/NEMO/couple/couple_ice/nemo-4.2.2/tests/test_CPL_OASIS/EXP00/namelist_ref .
ln -fs /rhome/soo/NEMO/couple/couple_ice/nemo-4.2.2/tests/test_CPL_OASIS/EXP00/namelist_ice_cfg .
ln -fs /rhome/soo/NEMO/couple/couple_ice/nemo-4.2.2/tests/test_CPL_OASIS/EXP00/namelist_ice_ref .
#################################################################################
#for couple
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/data_oasis3_mct/v4.2.2/grid_mask_ORCA1/modify/grids_t62.nc ./grids.nc
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/data_oasis3_mct/v4.2.2/grid_mask_ORCA1/modify/masks_t62.nc ./masks.nc
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/data_oasis3_mct/v4.2.2/namcouple_t62 ./namcouple
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/data_oasis3_mct/v4.2.2/weights_*.nc .
########soojin

if [ linux_intel = dec ] ; then
	datasize=1048576
	stacksize=3276800
else
	datasize=unlimited
	stacksize=unlimited
fi
ulimit -c $datasize
ulimit -s $stacksize
here_dir=`pwd`
if [ nml_linux_intel = compas_linux -a mpi != single -a mpi != thread ] ; then
    sed -n "1,12p" $HOME/node_list >$here_dir/hostfile
    sed 's/^/ssh /g' $here_dir/hostfile | sed 's/$/ "date"/g' >force_mount.sh
    chmod a+x force_mount.sh
    ./force_mount.sh
	ln -fs $PROG.parm                       fort.95
    /opt/mpich/myrinet/pgi/bin/mpirun -nolocal -np 12 -machinefile $here_dir/hostfile $here_dir/$PROG.x 1>$here_dir/${PROG}out.ft$hx 2>&1
else
   ln -fs $PROG.parm                       fort.95
#soojin_couple
#   mpirun -machinefile $PBS_NODEFILE -np 12 ./$PROG.x 1>fcstout.ft$fh 2>&1
 mpirun -machinefile $PBS_NODEFILE -bootstrap ssh -np 12 ./$PROG.x : -np 96 ./nemo
fi
#
stat=$?
if [ $stat -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	exit 8
fi
grep 'NaN' fcstout.ft$fh
if [ $? -eq 0 ]; then
	echo "The run has NaN crushed !!!" >> ERROR.out
	exit 8
fi
grep ' nan ' fcstout.ft$fh
if [ $? -eq 0 ]; then
	echo "The run has nan crushed !!!" >> ERROR.out
	exit 8
fi
grep '<WARNING>:' fcstout.ft$fh >>ERROR.out
rm -f fort.[0-9]* filenv.$$ >/dev/null
if [ linux_intel = x1e ]; then
	rm -f $FILENV
fi
#
echo "`date` $0: fcst is completely ended"
exit 0
