#!/bin/sh
#PBS -l nodes=1:ppn=1
#PBS -V
##PBS -j eo
#------------------------------------------------------------------end_of_header
#
# fgb
#
#  $1 ... starting forecast hour
#  $2 ... ending forecast hour
#  $3 ... forecast hour increment
#
#  This script assumes that the input flx file is the form flx.ftxx
#  The output flux and surface file is the form fgb.ftxx
#
fhs=${fhs:=$1}
fhe=${fhe:=$2}
fhinc=${fhinc:=$3}
EXECDIR=${EXECDIR:=$4}
if [ "$fhinc" = "" ] ; then
	echo "`date` $0: argument error" >>ERROR.out
	exit 8
fi
if [ "$EXECDIR" != "" ]; then
	cd $EXECDIR
fi
#
# FGB_POST
#
PROG=fgb
cat >$PROG.parm <<EOF
 &NAMFGB
 FHS=$fhs.,FHE=$fhe.,FHINC=$fhinc.,
 &END
EOF
if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
fi
if [ linux_intel = cray -o linux_intel = t90 -o linux_intel = t3e ] ; then
	assign -R
fi
#
rm -f $PROG.x
#
if [ linux_intel = dec ];then
   ulimit -s 1024000
else
   ulimit -s unlimited
fi
#
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/$PROG.x $PROG.x
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp fort.1
 ./$PROG.x <$PROG.parm 1>$PROG.out 2>&1
#
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	exit 8
fi
rm -f filenv.$$ >/dev/null 
#
echo "`date` $0: fgb is completely ended"
exit 0
