#!/bin/sh
#PBS -l nodes=1:ppn=1
#PBS -V
##PBS -j eo
#------------------------------------------------------------------end_of_header
#
# pgb
#
#  $1 ... starting forecast hour
#  $2 ... ending forecast hour
#  $3 ... forecast hour increment
#
#  This script assumes that the input sigma file is the form sig.ftxx
#  The output pressure file is the form pgb.ftxx
#
phs=${phs:=$1}
phe=${phe:=$2}
phinc=${phinc:=$3}
EXECDIR=${EXECDIR:=$4}
if [ "$phinc" = "" ] ; then
	echo "`date` $0: argument error" >>ERROR.out
	exit 8
fi
if [ "$EXECDIR" != "" ]; then
	cd $EXECDIR
fi
#
PROG=pgb
cat >$PROG.parm <<EOF
 &NAMPGB
 ICEN2=1,
 FHS=$phs.,FHE=$phe.,FHINC=$phinc.,
 KEID=0,
 MGRID=0,
 &END
EOF
if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
fi
if [ linux_intel = cray -o linux_intel = t90 -o linux_intel = t3e ] ; then
	assign -R
fi
#
rm -f $PROG.x
#
if [ linux_intel = dec ]; then
   ulimit -s 1024000
else
   ulimit -s unlimited
fi
#
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/$PROG.x $PROG.x
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp fort.1
 ./$PROG.x <$PROG.parm 1>$PROG.out 2>&1
#
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	exit 8
fi
rm -f filenv.$$ >/dev/null
#
echo "`date` $0: pgb is completely ended"
exit 0
