#!/bin/sh
if [ $# -ne 0 ] ; then
	echo $0:error in the number of arguments
	exit 8
fi
#
#  create ctl file for nc files
#
/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/runscr/roms_makectl `pwd`
#
#  input netcdf file description file
#
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/varinfo.dat .
#
PROG=roms
rm -f $PROG.x
ln -fs @MODEL_DIR@/bin/${PROG}.x $PROG.x
