#!/bin/sh
set -x
#
#  Pre-proccess for smp 
#
#  $1 is starting date
#  $2 is ending date
#  $3 is output sigma file name
#  $4 is output sfc file name
#
STIME=$1
ETIME=$2
OUT_SIG_FILE=$3
OUT_SFC_FILE=$4
#
PROG=presmp
cat >$PROG.parm <<EOF
 &NAMTIME
  STIME=$STIME, ETIME=$ETIME,
 &END
EOF
#
#
#  Execute forecast
#
if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
else
        rm -f fort.[0-9]* 2>/dev/null
fi

if [ linux_intel = cray -o linux_intel = t90 -o linux_intel = t3e ] ; then
        assign -R
fi
ln -fs orogrd.smth                         fort.24
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp        fort.1
rm -f $PROG.x
ln -s /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/${PROG}.x $PROG.x
./$PROG.x < $PROG.parm 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	exit 8
fi
rm -f fort.[0-9]*
mv scmini.ft00 $OUT_SIG_FILE
mv sfcini.ft00 $OUT_SFC_FILE
exit 0
