#!/bin/sh
#PBS -l nodes=3:ppn=36
#PBS -V
##PBS -j eo
#------------------------------------------------------------------end_of_header
set -ax
if [ "$EXECDIR" != "" ]; then
    cd $EXECDIR
fi
#
#  execute forecast.
#
#  $1 ... starting forecast hour
#  $2 ... ending   forecast hour
#  $3 ... base field interval (hour)
#  $4 ... regional field output interval (hour)
#

#
h=${h:=$1}
hx=${hx:=$2}
inchour=${inchour:=$3}
prthour=${prthour:=$4}
if [ "$prthour" = "" ] ; then
    echo "`date` $0: argument error" >>ERROR.out
    exit 8
fi
#
PROG1=rfcst
PROG1_NPES=
PROG2=roms
PROG2_NPES=
#
fh=`/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/etc/fhour r_sigit`
#
# SWRMDC
#
swrmdc=`fgrep SWRMDC /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/define.h | fgrep -v undef | fgrep define | wc -l`
if [ $swrmdc -eq 1 ]; then
    mon=01
    while [ $mon -le 12 ]; do
        ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/global_aeropac3a.m${mon}.txt .
        mon=`expr $mon + 1`
        if [ $mon -lt 10 ]; then
            mon=0$mon
        fi
    done
fi
#
if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
else
        rm -f fort.[0-9]* 2>/dev/null
fi
#
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp               fort.1
ln -fs $EXECDIR/co2con                            fort.15
ln -fs $EXECDIR/r_mtnvar                          fort.24
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/o3prod.clim.asc                  fort.28
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/o3loss.clim.asc                  fort.29
ln -fs $EXECDIR/r_sigit                           fort.30
ln -fs $EXECDIR/r_sigitdt                         fort.31
ln -fs $EXECDIR/r_sfci                            fort.32
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/flwdirGSWP2.hlf.asc              fort.41
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/tune.t42l18.amip.ewmrg           fort.43
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/gcmo3.asc                        fort.48
#
cp /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con_rop/varinfo.dat .
rm -f $PROG1.x $PROG2.x
if [ mpi = mpi -o mpi = hybrid ] ; then
    ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/${PROG1}_par.x $PROG1.x
    ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/${PROG2}.x $PROG2.x
	ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/runscr/${PROG2}.parm ${PROG2}.parm
else
    ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/${PROG1}.x $PROG1.x
    ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/${PROG2}.x $PROG2.x
	ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/runscr/${PROG2}.parm ${PROG2}.parm
fi
#
if [ linux_intel = dec ] ; then
    datasize=1048576
    stacksize=3276800
else
    datasize=unlimited
    stacksize=unlimited
fi
ulimit -s $datasize
ulimit -c $stacksize
#
here_dir=`pwd`
rm -f myfile
touch myfile
cat <<EOF >myfile
./$PROG1.x:$PROG1_NPES
./$PROG2.x $PROG2.parm:$PROG2_NPES
EOF
#
if [ mpi = mpi -o mpi = hybrid ] ; then
	ln -fs $PROG1.parm fort.95
    #mpirun -machinefile $PBS_NODEFILE -np 12 -cmdfile myfile 1> r_fcstout.ft$hx 2>&1
    mpiexec -n $PROG1_NPES ./$PROG1.x : -n $PROG2_NPES ./$PROG2.x $PROG2.parm 1> r_fcstout.ft$hx 2>&1
else
	echo "couping with single or thread mode not possible" >>ERROR.out
	echo "couping with single or thread mode not possible"
	exit 8
fi
grep 'NaN' r_fcstout.ft$hx
if [ $? -eq 0 ]; then
        echo "The run has NaN crushed !!!" >> ERROR.out
        exit 8
fi
grep 'nan' r_fcstout.ft$hx
if [ $? -eq 0 ]; then
        echo "The run has nan crushed !!!" >> ERROR.out
        exit 8
fi
grep '<WARNING>:' r_fcstout.ft$hx >>ERROR.out
#
exit 0
