#!/bin/sh
#PBS -l nodes=3:ppn=36
#PBS -V
##PBS -j eo
#------------------------------------------------------------------end_of_header
set -ax
#
if [ linux_intel = linux_pgi ]; then
export NO_STOP_MESSAGE=1
fi
export MPIEXEC_TIMEOUT=15   # to prevent qdel error
#
if [ "$EXECDIR" != "" ]; then
    cd $EXECDIR
fi
#
#  execute forecast.
#
#  $1 ... starting forecast hour
#  $2 ... ending   forecast hour
#  $3 ... base field interval (hour)
#  $4 ... regional field output interval (hour)
#
PROG=rfcst
#
#  Execute forecast
#
h=${h:=$1}
hx=${hx:=$2}
inchour=${inchour:=$3}
prthour=${prthour:=$4}
if [ "$prthour" = "" ] ; then
    echo "`date` $0: argument error" >>ERROR.out
    exit 8
fi
#
fh=`/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/etc/fhour r_sigit`
#
# SWRMDC
#
swrmdc=`fgrep SWRMDC /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/define.h | fgrep -v undef | fgrep define | wc -l`
if [ $swrmdc -eq 1 ]; then
    mon=01
    while [ $mon -le 12 ]; do
        ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/global_aeropac3a.m${mon}.txt .
        mon=`expr $mon + 1`
        if [ $mon -lt 10 ]; then
            mon=0$mon
        fi
    done
fi
#
if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
else
        rm -f fort.[0-9]* 2>/dev/null
fi
#
sleep 10
#
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp               fort.1
ln -fs $EXECDIR/co2con                            fort.15
ln -fs $EXECDIR/r_mtnvar                          fort.24
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/o3prod.clim.asc                  fort.28
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/o3loss.clim.asc                  fort.29
ln -fs $EXECDIR/r_sigit                           fort.30
ln -fs $EXECDIR/r_sigitdt                         fort.31
ln -fs $EXECDIR/r_sfci                            fort.32
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/flwdirGSWP2.hlf.asc              fort.41 
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/tune.t42l18.amip.ewmrg           fort.43
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/con/gcmo3.asc                        fort.48
#
rm -f $PROG.x
if [ mpi = mpi -o mpi = hybrid ] ; then
	ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/${PROG}_par.x $PROG.x
else
	ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/${PROG}.x $PROG.x
fi
#
if [ linux_intel = dec ] ; then
    datasize=1048576
    stacksize=3276800
else
    datasize=unlimited
    stacksize=unlimited
fi
ulimit -s $datasize
ulimit -c $stacksize
#
here_dir=`pwd`
if [ nml_linux_intel = compas_linux -a mpi != single -a mpi != thread ] ; then
    sed -n "1,${FCST_NPES}p" $HOME/node_list >$here_dir/hostfile
	ln -fs $PROG.parm fort.95
    /opt/mpich/myrinet/pgi/bin/mpirun -nolocal -np ${FCST_NPES} -machinefile $here_dir/hostfile $here_dir/$PROG.x 1>$here_dir/r_fcstout.ft$hx 2>&1
else
	ln -fs $PROG.parm fort.95
	mpirun -machinefile $PBS_NODEFILE -np 12 ./$PROG.x 1> r_fcstout.ft$hx 2>&1
fi
if [ $? -ne 0 ] ; then
	echo "r_fcst failed" >>ERROR.out
	exit 8
fi
grep 'NaN' r_fcstout.ft$hx
if [ $? -eq 0 ]; then
        echo "The run has NaN crushed !!!" >> ERROR.out
        exit 8
fi
grep ' nan ' r_fcstout.ft$hx
if [ $? -eq 0 ]; then
        echo "The run has NaN crushed !!!" >> ERROR.out
        exit 8
fi
grep '<WARNING>:' r_fcstout.ft$hx >>ERROR.out
rm -f fort.[0-9]* >/dev/null
#
exit 0
