#!/bin/sh
set -x
#
# set up the initial and base field for idealized experiments 
#
if [ $# -lt 6 ] ; then
	echo $0: wrong number of arguments
fi
syyyy=`echo $1 | cut -d':' -f1`
smm=`echo $1 | cut -d':' -f2`
sdd=`echo $1 | cut -d':' -f3`
shh=`echo $1 | cut -d':' -f4`
iexp=$2
clevs=`echo $3 | cut -d':' -f1`
isen=`echo $3 | cut -d':' -f2`
dsig=`echo $3 | cut -d':' -f3`
theta0=`echo $4 | cut -d':' -f1`
ta=`echo $4 | cut -d':' -f2`
z0=`echo $5 | cut -d':' -f1`
r1=`echo $5 | cut -d':' -f2`
r2=`echo $5 | cut -d':' -f3`
OUTRSIG=`echo $6 | cut -d':' -f1`
#
PROG=rinpg
if [ "$iexp" = warm ]; then
cat > ${PROG}.parm <<EOF
 &NAMRIN 
 FHOUR=0.,
 IDATE(1)=${shh},
 IDATE(2)=${smm},
 IDATE(3)=${sdd},
 IDATE(4)=${syyyy},
 CONLEVS=${clevs},
 ISENLEVS=${isen},
 DS=${dsig},
 THETA0=${theta0},
 TA=${ta},
 Z0=${z0},
 RC=${r1},
 RE=${r2},
/
EOF
elif [ "$iexp" = cold ]; then
cat > ${PROG}.parm <<EOF
 &NAMRIN 
 FHOUR=0.,
 IDATE(1)=${shh},
 IDATE(2)=${smm},
 IDATE(3)=${sdd},
 IDATE(4)=${syyyy},
 CONLEVS=${clevs},
 ISENZ=${isen},
 DS=${dsig},
 THETA0=${theta0},
 TA=${ta},
 Z0=${z0},
 XR=${r1},
 ZR=${r2},
/
EOF
elif [ "$iexp" = hill ]; then
cat > ${PROG}.parm <<EOF
 &NAMRIN 
 FHOUR=0.,
 IDATE(1)=${shh},
 IDATE(2)=${smm},
 IDATE(3)=${sdd},
 IDATE(4)=${syyyy},
 CONLEVS=${clevs},
 ISENLEVS=${isen},
 DS=${dsig},
 THETA0=${theta0},
 U0=${ta},
 HM=${z0},
 XA=${r1},
/
EOF
echo "ideal test: $iexp"
fi
cat rsm.parm >>$PROG.parm
if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
else
        rm -f fort.[0-9]* 2>/dev/null
fi

if [ linux_intel = cray -o linux_intel = t90 ] ; then
	assign -R
fi
ln -fs $OUTRSIG                          fort.51
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp      fort.1
#
if [ linux_intel = dec ]; then
  ulimit -s 1024000
else
  ulimit -s unlimited
fi
#
rm $PROG.x 2>/dev/null
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/$PROG.x $PROG.x
./$PROG.x <$PROG.parm 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo `date` - $PROG execution failed >>ERROR.out
	exit 8
fi
