#!/bin/sh
set -x
#
if [ $# -ne 3 ] ; then
	echo $0: wrong number of arguments
fi
SFCFTYP=$1
INGSIG=`echo $2 | cut -d':' -f1`
INGSFC=`echo $2 | cut -d':' -f2`
OUTRSIG=`echo $3 | cut -d':' -f1`
OUTRSFC=`echo $3 | cut -d':' -f2`
#
PROG=rinpg
echo " &NAMRIN                                         "  >$PROG.parm
echo "    SFCFTYP='$SFCFTYP',                          " >>$PROG.parm
echo "/                                                " >>$PROG.parm
cat rsm.parm >>$PROG.parm
if [ linux_intel = x1e ] ; then
        FILENV=filenv.$$
        export FILENV
        assign -R
else
        rm -f fort.[0-9]* 2>/dev/null
fi

if [ linux_intel = cray -o linux_intel = t90 ] ; then
	assign -R
fi
ln -fs $INGSIG                           fort.11
ln -fs $INGSFC                           fort.12
ln -fs r_smooth_oroggd                   fort.14
ln -fs $OUTRSIG                          fort.51
ln -fs $OUTRSFC                          fort.52
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/namelist.gmp      fort.1
#
if [ linux_intel = dec ]; then
  ulimit -s 1024000
else
  ulimit -s unlimited
fi
#
rm $PROG.x 2>/dev/null
ln -fs /rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/runs_gmp/../srcs_gmp/bin/$PROG.x $PROG.x
./$PROG.x <$PROG.parm 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo `date` - $PROG execution failed >>ERROR.out
	exit 8
fi
