#!/bin/sh
#
#  Restart
#
#  Get fhour from sigit file and return its value
#
h=`/rhome/soo/NEMO/couple/couple_ice/gmp_v3.2/libs_gmp/etc/fhour sigit`
h=`expr $h + 0`
if [ $h -lt 10 ] ; then h=0$h ; fi
echo $h
echo "Restarting from $h" >>ERROR.out
